#!/bin/sh

# Verifica o PHPStan
./vendor/bin/phpstan --memory-limit=2G
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar... 😉";
    exit 1;
fi;

# Executa os testes
php artisan test --parallel | php
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... 😉";
    exit 1;
fi;

# Formata com Prettier os arquivos em resources/
echo "Formatando arquivos com Prettier..."
npx prettier --write resources/
if [ $? -ne 0 ]; then
    echo "Erro ao formatar com Prettier.";
    exit 1;
fi;

# Roda o lint com ESLint
echo "Executando ESLint..."
npx eslint . --fix
if [ $? -ne 0 ]; then
    echo "Erro ao executar ESLint.";
    exit 1;
fi;

# Formata arquivos PHP modificados com Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
done;

exit 0;
